package backend

import (
	"regexp"
	"strings"

	"github.com/bobg/go-generics/v4/slices"
)

type Model int

const (
	ModelQwen3Embedding8B4B_DWQ     Model = 1
	ModelAppleNLContextualEmbedding Model = 2
)

func (m Model) String() string {
	switch m {
	case ModelQwen3Embedding8B4B_DWQ:
		return "mlx-community/Qwen3-Embedding-8B-4bit-DWQ"
	case ModelAppleNLContextualEmbedding:
		return "apple/nlcontextualembedding"
	}

	panic("unknown model")
}

var referenceRegex = regexp.MustCompile(`\[([^\]]+)\]`)

type Word struct {
	Word       string `json:"word"`
	Author     string `json:"author"`
	Definition string `json:"definition"`
	Example    string `json:"example"`
}

type Definition struct {
	Word     `json:",inline"`
	Features []Feature `json:"features,omitempty"`
}

type Feature struct {
	Phrase        string              `json:"phrase"`
	Autogenerated bool                `json:"autogenerated"`
	Embeddings    map[Model]Embedding `json:"embeddings,omitempty"`
}

type Embedding []float32

type SimilarDefinition struct {
	Word     `json:"definition"`
	Distance float64 `json:"distance"`
	Phrase   string  `json:"phrase"`
}

func NewEmbeddingFromFloat64(vector []float64) Embedding {
	embedding := make(Embedding, len(vector))

	for i, v := range vector {
		embedding[i] = float32(v)
	}

	return embedding
}

func SplitDefinition(definition string) []string {
	lines := strings.Split(definition, "\n")

	// Filter out empty lines.
	lines = slices.Map(lines, func(line string) string {
		line = strings.TrimSpace(line)

		line = referenceRegex.ReplaceAllString(line, "$1")

		return line
	})

	lines = slices.Filter(lines, func(line string) bool {
		return line != ""
	})

	return lines
}
