package backend

import (
	"regexp"
	"strings"

	"github.com/bobg/go-generics/v4/slices"
)

var referenceRegex = regexp.MustCompile(`\[([^\]]+)\]`)

type Definition struct {
	Word       string          `json:"word"`
	Definition string          `json:"definition"`
	Example    string          `json:"example"`
	Embeddings []SubDefinition `json:"embeddings,omitempty"`
}

type SimilarDefinition struct {
	Definition `json:"definition"`
	Phrase     string  `json:"phrase"`
	Distance   float64 `json:"distance"`
}

type SubDefinition struct {
	Phrase        string `json:"phrase"`
	Vector        Vector `json:"vector,omitempty"`
	Autogenerated bool   `json:"autogenerated"`
}

type Vector []float32

func NewEmbeddingFromFloat64(vector []float64) Vector {
	embedding := make(Vector, len(vector))

	for i, v := range vector {
		embedding[i] = float32(v)
	}

	return embedding
}

func SplitDefinition(definition string) []string {
	lines := strings.Split(definition, "\n")

	// Filter out empty lines.
	lines = slices.Map(lines, func(line string) string {
		line = strings.TrimSpace(line)

		line = referenceRegex.ReplaceAllString(line, "$1")

		return line
	})

	lines = slices.Filter(lines, func(line string) bool {
		return line != ""
	})

	return lines
}
