-- sqlite
CREATE TABLE words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT NOT NULL,
    definition TEXT NOT NULL,
    example TEXT NOT NULL,
    author TEXT NOT NULL,
    UNIQUE (word, definition)
) STRICT;

CREATE TABLE word_features (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word_id INTEGER NOT NULL,
    phrase TEXT NOT NULL,
    autogenerated INTEGER NOT NULL DEFAULT 0,
    UNIQUE (word_id, phrase),
    FOREIGN KEY (word_id) REFERENCES words (id)
) STRICT;

CREATE TABLE embedding_models (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    UNIQUE (name)
) STRICT;

CREATE TABLE embeddings (
    word_feature_id INTEGER NOT NULL,
    embedding_model_id INTEGER NOT NULL,
    embedding BLOB NOT NULL CHECK (vec_length(embedding) >= 256),
    PRIMARY KEY (word_feature_id, embedding_model_id),
    FOREIGN KEY (word_feature_id) REFERENCES word_features (id),
    FOREIGN KEY (embedding_model_id) REFERENCES embedding_models (id)
) STRICT;

INSERT
    OR REPLACE INTO embedding_models (id, name)
VALUES
    (1, 'mlx-community/Qwen3-Embedding-8B-4bit-DWQ'),
    (2, 'apple/nlcontextualembedding');
