CREATE TABLE words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT NOT NULL,
    definition TEXT NOT NULL,
    example TEXT NOT NULL,
    UNIQUE (word, definition)
) STRICT;

CREATE TABLE embeddings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    phrase TEXT NOT NULL,
    autogenerated INTEGER NOT NULL DEFAULT 0,
    embedding BLOB NOT NULL CHECK (vec_length(embedding) = 4096),
    UNIQUE (phrase)
) STRICT;

CREATE TABLE word_embeddings (
    word_id INTEGER NOT NULL,
    embedding_id INTEGER NOT NULL,
    PRIMARY KEY (word_id, embedding_id),
    FOREIGN KEY (word_id) REFERENCES words (id),
    FOREIGN KEY (embedding_id) REFERENCES embeddings (id)
) STRICT;
