package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/url"
	"os"

	"github.com/Crystalix007/reverse-dict/backend"
)

func main() {
	ctx := context.Background()

	if err := reingest(ctx); err != nil {
		slog.ErrorContext(ctx, "reingesting words", slog.Any("error", err))
		os.Exit(1)
	}
}

func reingest(ctx context.Context) error {
	sqlite, err := backend.NewSQLiteVec(
		ctx,
		"words.db",
	)
	if err != nil {
		return fmt.Errorf("creating SQLiteVec: %w", err)
	}

	swama, err := backend.NewSwamaAPI(
		url.URL{
			Scheme: "http",
			Host:   "127.0.0.1:28100",
		},
	)
	if err != nil {
		return fmt.Errorf("creating SwamaAPI: %w", err)
	}

	for word, err := range sqlite.GetWords(ctx) {
		slog.InfoContext(
			ctx,
			"reingesting definition",
			slog.String("word", word.Word),
		)

		if err != nil {
			return fmt.Errorf("getting definitions: %w", err)
		}

		generatedDefs, err := swama.RephraseDefinition(ctx, *word)
		if err != nil {
			slog.ErrorContext(
				ctx,
				"rephrasing definition failed",
				slog.String("word", word.Word),
				slog.Any("error", err),
			)

			continue
		}

		embeddings, err := swama.Embed(ctx, generatedDefs...)
		if err != nil {
			slog.ErrorContext(
				ctx,
				"embedding definitions failed",
				slog.String("word", word.Word),
				slog.Any("error", err),
			)

			continue
		}

		features := make([]backend.Feature, len(generatedDefs))

		for i, embedding := range embeddings {
			features[i] = backend.Feature{
				Embeddings: map[backend.Model]backend.Embedding{
					backend.ModelQwen3Embedding8B4B_DWQ: backend.NewEmbeddingFromFloat64(embedding),
				},
				Phrase:        generatedDefs[i],
				Autogenerated: true,
			}
		}

		definition := backend.Definition{
			Word:     *word,
			Features: features,
		}

		if _, err := sqlite.AddDefinition(ctx, definition); err != nil {
			return fmt.Errorf("adding word: %w", err)
		}
	}

	return nil
}
