package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/url"
	"os"

	"github.com/Crystalix007/reverse-dict/backend"
)

func main() {
	ctx := context.Background()

	if err := reingest(ctx); err != nil {
		slog.ErrorContext(ctx, "reingesting words", slog.Any("error", err))
		os.Exit(1)
	}
}

func reingest(ctx context.Context) error {
	sqlite, err := backend.NewSQLiteVec(
		ctx,
		"words.db?_journal_mode=WAL",
	)
	if err != nil {
		return fmt.Errorf("creating SQLiteVec: %w", err)
	}

	swama, err := backend.NewSwamaAPI(
		url.URL{
			Scheme: "http",
			Host:   "127.0.0.1:28100",
		},
	)
	if err != nil {
		return fmt.Errorf("creating SwamaAPI: %w", err)
	}

	for definition, err := range sqlite.GetDefinitions(ctx) {
		slog.InfoContext(
			ctx,
			"reingesting definition",
			slog.String("word", definition.Word),
		)

		if err != nil {
			return fmt.Errorf("getting definitions: %w", err)
		}

		generatedDefs, err := swama.RephraseDefinition(ctx, *definition)
		if err != nil {
			return fmt.Errorf("rephrasing definition: %w", err)
		}

		embeddings, err := swama.Embed(ctx, generatedDefs...)
		if err != nil {
			return fmt.Errorf("embedding definitions: %w", err)
		}

		subDefinitions := make([]backend.SubDefinition, len(generatedDefs))

		for i, embedding := range embeddings {
			subDefinitions[i] = backend.SubDefinition{
				Phrase:        generatedDefs[i],
				Vector:        backend.NewEmbeddingFromFloat64(embedding),
				Autogenerated: true,
			}
		}

		definition.Embeddings = subDefinitions

		if _, err := sqlite.AddWord(ctx, *definition); err != nil {
			return fmt.Errorf("adding word: %w", err)
		}
	}

	return nil
}
